// Generated by gencpp from file listen/listenRequest.msg
// DO NOT EDIT!


#ifndef LISTEN_MESSAGE_LISTENREQUEST_H
#define LISTEN_MESSAGE_LISTENREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace listen
{
template <class ContainerAllocator>
struct listenRequest_
{
  typedef listenRequest_<ContainerAllocator> Type;

  listenRequest_()
    {
    }
  listenRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::listen::listenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::listen::listenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct listenRequest_

typedef ::listen::listenRequest_<std::allocator<void> > listenRequest;

typedef boost::shared_ptr< ::listen::listenRequest > listenRequestPtr;
typedef boost::shared_ptr< ::listen::listenRequest const> listenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::listen::listenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::listen::listenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace listen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::listen::listenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::listen::listenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::listen::listenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::listen::listenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::listen::listenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::listen::listenRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::listen::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::listen::listenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::listen::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "listen/listenRequest";
  }

  static const char* value(const ::listen::listenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::listen::listenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::listen::listenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::listen::listenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct listenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::listen::listenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::listen::listenRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LISTEN_MESSAGE_LISTENREQUEST_H
